Config = {}

Config.DB = {}

Config.DB.Host = HOST_PLACEHOLDER
Config.DB.Database = DATABASENAME_PLACEHOLDER
Config.DB.Port = PORT_PLACEHOLDER
Config.DB.Username = USERNAME_PLACEHOLDER
Config.DB.Password = PASSWORD_PLACEHOLDER